language: python

sudo: false

dist: precise

services: cassandra

env:
  matrix:
    - TOX_ENV=py27-django19
    - TOX_ENV=py35-django19
    - TOX_ENV=py27-django110
    - TOX_ENV=py35-django110
    - TOX_ENV=py27-django111
    - TOX_ENV=py35-django111
    - TOX_ENV=py35-djangomaster
  global:
    - CASS_DRIVER_NO_CYTHON=1

python:
  - "3.5"

addons:
  apt:
    packages:
    - build-essential
    - python-dev
    - pypy-dev
    - libev4
    - libev-dev

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
